repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.9
      - id: black
        alias: black-on-ci
        args: ["--check --diff"]
        stages: [manual]
  -   repo: https://github.com/pycqa/flake8
      rev: 5.0.3
      hooks:
      -   id: flake8
