version: '3.0'

services:

  magicparse:
    build:
      context: .
      args:
        - USERNAME=magicparse
    tty: true
    working_dir: /home/src/magicparse
    volumes:
      - .:/home/src/magicparse
      - /home/src/magicparse/.venv/
