[tool.poetry]
name = "magicparse"
version = "0.0.0"
description = "Declarative parser 🛸"
authors = ["Smartway <dev@zero-gachis.com>"]
readme = "README.md"
repository = "https://github.com/ZeroGachis/magicparse"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
flake8 = "^6.1.0"
pytest = "^7.4.4"
awscli = "~1"
flake8-pyproject = "~1.2.3"

[build-system]
requires = ["poetry-core>=1.2.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
pattern  = "^(?P<base>\\d+\\.\\d+\\.\\d+)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "E722"]
exclude = [".git/", ".pytest_cache/", ".venv"]

[tool.pytest.ini_options]
python_files = ["tests/*"]